/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exampleOwnerSol from "./Example_Owner.sol";
export type { exampleOwnerSol };
import type * as external from "./external";
export type { external };
import type * as onChainDeployments from "./on-chain-deployments";
export type { onChainDeployments };
